### ISSUE TITLE
EXT to read large csv files line per line

### ISSUE THREAD

**Issue by aWuttig** [cobwebch/svconnector_csv#2]
Hey,
i put my code into sep. extension to read large csv file line per line. Have a look on it:

https://github.com/portrino/svconnector_csv_extended

**Comment by fsuter** [comment]
Interesting. Thanks for sharing. I'll a mention of your extension in the manual for the next version. Would that be fine with you?

**Comment by aWuttig** [comment]
Of course! Thank You. I will write a short documentation into the
Readme.md.

Best Regards
André

Am 03.10.2017 11:36 schrieb "François Suter" <notifications@github.com>:

Interesting. Thanks for sharing. I'll a mention of your extension in the
manual for the next version. Would that be fine with you?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cobwebch/svconnector_csv/issues/2#issuecomment-333790852>,
or mute the thread

**Comment by fsuter** [comment]
Gosh, I only realize now that it's been more than a year! So sorry about the delay.
