### ISSUE TITLE
Multiline field breaks import

### ISSUE THREAD

**Issue by sruegg** [cobwebch/svconnector_csv#4]
Hello,

Since the following update (> 2.2.0 I think) : https://github.com/cobwebch/svconnector_csv/blob/36195c386a8ca41226cc5770e6454ca2572edfb8/Classes/Service/ConnectorCsv.php#L208

If you have some multiline field it completely breaks the import as you split content by new line chars.

I assume there is a good reason for not using the good old one [fgetcsv](http://www.php.net/manual/en/function.fgetcsv.php) php function here?

Best Regards,
Sébastien

**Comment by fsuter** [comment]
Now that's interesting because I caught myself in this trap (of my own design) recently and didn't think about this change as the culprit. The change away from fgetcsv is because I implemented a central file-reading utility to harmonize all connector services. Now here's one obvious drawback. I'll have to see how I can work around that.

Thanks for reporting!

**Comment by sruegg** [comment]
I totally understand why you did it now 😉 

Just thinking: what about the preg_split with the column separator before the new line.
i.e. with ";" as column separator: `preg_split("[;](\r\n|\n|\r)", $fileContent)`

This is not working with CSV without column separator at the end of the line.

Another possibility I see would be to build the lines with fgetcsv first (as the function handles well that multilines field case).

Glad to help testing and/or pull request if needed.

**Comment by fsuter** [comment]
I will first investigate the possibility to use fgetcsv despite the central file-reading utility, because that would be the easiest. I'll keep you posted for testing if needed. Thanks for volunteering.

**Comment by fsuter** [comment]
The attached archive contains two patch files, one applies to "svconnector", the other to "svconnector_csv". Could you give them a try?

I couldn't really find a solution as smart as I would have liked, so I decided to implement a solution where there's a new API function that reads the remote data and stores it locally in a temporary file. The specific connector service can then read the temporary file. This makes it possible for "svconnector_csv" to return to using fgetcsv.

[patches.zip](https://github.com/cobwebch/svconnector_csv/files/2388706/patches.zip)

**Comment by sruegg** [comment]
Wow! That was quick 😄 !
Just tested and everything seems to be correct with multilines fields.

Your solution works! Thanks!

**Comment by fsuter** [comment]
Part related to svconnector applied in https://github.com/cobwebch/svconnector/issues/14
