### ISSUE TITLE
non-deletable files break functionality

### ISSUE THREAD

**Issue by DavidBruchmann** [cobwebch/svconnector_csv#6]
In Classes/Service/ConnectorCsv.php in line 214 files get deleted:
```
unlink($temporaryFile);
```
If this is not working for some reason any further functionality is interrupted and therefore not working. Working on Windows it might be more probable that this line is not working but in general the OS doesn't matter so much. I propose the solution to change the line to
```
@unlink($temporaryFile);
```
OR to wrap the line in a `try {} catch ($e) {}` statement and log the error but proceed with the import.

**Comment by fsuter** [comment]
Indeed. Thanks for reporting.
